FROM node:13.12.0-alpine

RUN npm i -g ganache-cli

EXPOSE 7545

ENTRYPOINT ganache-cli --host=0.0.0.0 -m='belt prize arrow cabbage banner proof word above ability helmet design rely' --networkId=5777 -p 7545 -l 80000000000
